### ISSUE TITLE
32bit CDRom repo not functioning and causing ubiquity to crash

### ISSUE THREAD

**Issue by charlesbodhi** [stacefauske/bodhibuilder_2.18.x_all#4]
When trying to install a copy of Bodhi5.0-legacy-beta I made with BB-2.18.2 I got a pop-up about the cdrom repository being invalid. After clicking that away the installer crashed. No logs available but I took a screenshot, it only refers to apt being unable to configure the cdrom repository.

Related (though about 64bit) is a typo in current line 808 where I miss a leading space before the == 
This results in an Error mentioned in the bodhibuilder output screen, not sure it really affects the IF condition you try to have.

Also noticed you have implemented the trusted=yes --> file only for 64 bit. Found nothing that could make the 32bit repo acceptable for apt.
Charles

**Comment by stacefauske** [comment]
Was it an online or offline install?
I was not having this issue. When I rolled a fully upgraded legacy install, I didn't even need any deb files in the cdrom pool. It just installed like a champ.
When I do the install of bodhibuilder, I usually do this in order:
> sudo dpkg -P bodhibuilder
> sudo rm -rf /etc/bodhibuilder/
> sudo dpkg -i bodhibuilder_(version)_all.deb
Just to make sure that I'm starting from a fresh install. I think I may need to add a pre-install script to remove some things before actually installing.

**Comment by stacefauske** [comment]
Good catch on the if statement. Corrected.

**Comment by stacefauske** [comment]
Ok, just had this happen on a fresh Bodhi install, dist-upgrade, sudo apt-get autoremove --purge, then upgrade of bodhibuilder to v2.18.2.
Investigating.

**Comment by stacefauske** [comment]
Removed v2.18.2 from sourceforge just now.
It worked yesterday in all of my tests but now it's failing. So I'll keep digging into it as time allows.

**Comment by charlesbodhi** [comment]
I have thoroughly looked at the script for all lines related to apt, packages download and cd rom creation. also making the repos on disk trusted or accepted using the sources.list.
You consequently were adding stuff to amd64 where there is almost nothing done in regard to i386. Even you did not create a Packages.gz in the i386 pool while this is a musthave for apt to see that dir as a repository.
As we don't know on what kind of hardware a user is going to install the iso we can not decide that the i386 repo is not important or remains unused.
If the amd64 iso did fully work,  then a sudden error after correcting the "typo" must be related to the if then else fi statement, me thinks. The whole condition could well have been skipped. When I have time i will compare the script with the bb logfile of my latest legacy attempt (typo not corrected) to see which log-items are missing.
The ubiquity crash may well have been caused by apt. As it could not pass the error about cdrom repo configuration apt possibly is locked.

**Comment by stacefauske** [comment]
I think that was it my friend, I re-added the line to create a Packages.gz, and now it is installing on the 32-bit again. (I was not aware that Packages.gz was necessary since for so many years remastersys never used a Packages.gz)
Please try the new v2.18.2 on my google drive. (I should have sent your email a link) If we find it acceptable, I'll clean up some comments and make the indents look nice before updating git.

**Comment by charlesbodhi** [comment]
Packages.gz is okay as it stops locking apt and thus ubiquity does not crash anymore. But that is only part of the problem. When you mount the iso you will notice that the dir /dists/pool/ is empty and the packages.gz file is empty too.
IMO what you did to make the 64 bit repos functional you have to do for the 32 bit repo too. That includes creating a trusted file and also downloading the latest debs. The missing release would not be important as we have trusted files while on a repo that is a factor to error the repo out because the security policy is very strict from 17.10 up.

I have not yet tested the 64 bit but will start with that tomorrow. I hope to find the mood and time at least.

**Comment by charlesbodhi** [comment]
Another thing is having the expected content twice in the /etc/apt/sources.list. I only had a quick glance at the part of the code responsabel for that but I know ubiquity removes the existing sources.list and starts a new sources.list from scratch by searching for a CDRom repo and creating a tmpfile holding the future line in the sources.list. So it does for all mirrors of the ubuntu repos and collects those temp files to write out the sources.list for the installed system. Looks like your method adds another ~ 50 lines.

**Comment by stacefauske** [comment]
Yes indeed, ubiquity is commenting out our sources.list and adding it's own version at the bottom, messing everything up in the installed system. /etc/apt/sources.list in the installed system basically becomes a 'stock' sources.list from the ubiquity installer. Already have a fix planned for that one.

As far as the included debs for the 32-bit, I agree that we need to add some of the debs back in (especially b43-fwcutter, bcmwl-kernel-source), but do we really need all of them? I will default to you since you're more familiar with the 32-bit than I am. If we don't, I will open a new issue and we can discuss which debs need to be included. Personally, I would be up for not including any debs in the package itself for both 64 & 32-bit. Conversely, if the source OS is online when a Dist spin is performed it will download all of the necessary debs and include them in the ISO spin, if it's offline, no debs downloaded. On second thought, I'm going to open a new issue so we can discuss this and it will have it's own thread.

**Comment by stacefauske** [comment]
Repo has been fixed for both 32 & 64 bit systems

**Comment by charlesbodhi** [comment]
Why do we keep a CDROM repo? We now have the File "repo" to work with. Apt
security restrictions do prevent making use of a CDRom Repo without a
proper release file. So the CDRom repo is not really fixed, apt refuses
access, so ubiquity has no CDRom repos available at installation time, but
ignores it. Thanks to the trusted=yes File/ option Ubiquity is allowed to
use the debs in pool. But the CDRom repo is still not in use!

Op do 30 aug. 2018 om 19:34 schreef sef <notifications@github.com>:

**Comment by stacefauske** [comment]
If you're talking about the cdrom repo that is in the live ISO's sources.list, isolinux puts that in there during iso creation. And I haven't looked into getting isolinux to stop doing it.

But if you're talking about the cdrom directory in the file repo, is there a reason to change it?
At the time we were troubleshooting and just doing what we could to get it working. So we had to switch to the file option rather than cdrom and I guess we just left cdrom the way it was probably because of exhaustion. However I can see that if we are ever faced with the necessity to switch it back for some odd reason, leaving it as cdrom will make it easier.

**Comment by charlesbodhi** [comment]
Apt produces an error about the CDROM not being usable. This seems to crash
ubiquity.. Where the file option is not seen as a repo but only a personal
collection of debs we probably don't need the packages.gz in there.
Bodhibuilder does no longer need to install the package dpkg-dev to do this
job only.

Op do 30 aug. 2018 om 20:57 schreef sef <notifications@github.com>:

**Comment by stacefauske** [comment]
This only happens with the 32-bit for you?

**Comment by charlesbodhi** [comment]
crashing was only in 32 bit yes. But apt refuses to handle the CDRom repo
under all archs.

Op zo 2 sep. 2018 om 02:48 schreef sef <notifications@github.com>:

**Comment by stacefauske** [comment]
This is on an ISO created from a fresh Bodhi install and which version of BB?
